import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import eslintConfigPrettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "prisma/generated/**",
    // Generated by scripts/build-runtime.mjs from runtime-src/ — linting build
    // output is meaningless (the warnings are esbuild's `x?.y()` statement style)
    // and its count creeps with every rebuild. Same reasoning as .prettierignore;
    // the real gates are `typecheck:runtime` on the source and the CI drift check.
    "public/runtime/*.js",
  ]),
]);

export default eslintConfig;
