// Bundles the runtime augment scripts (runtime-src/<entry>/index.ts) into
// self-contained classic IIFEs at public/runtime/<entry>.js.
//
// GENERATED OUTPUT — do not hand-edit public/runtime/*.js. Edit runtime-src/
// and run `npm run build:runtime` (or `npm run watch:runtime`).
import * as esbuild from "esbuild";

const banner = {
  js: "/* GENERATED by scripts/build-runtime.mjs — edit runtime-src/, then `npm run build:runtime`. Do not edit this file. */",
};

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: {
    loader: "runtime-src/loader/index.ts",
    "reskin-player": "runtime-src/reskin-player/index.ts",
    "demo-overlays": "runtime-src/demo-overlays/index.ts",
    "admin-toggle": "runtime-src/admin-toggle/index.ts",
  },
  outdir: "public/runtime",
  bundle: true,
  format: "iife",
  target: ["es2019"],
  sourcemap: "external",
  minify: false,
  charset: "utf8",
  legalComments: "none",
  banner,
  logLevel: "info",
};

if (process.argv.includes("--watch")) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("[build-runtime] watching runtime-src/…");
} else {
  await esbuild.build(options);
  console.log("[build-runtime] built public/runtime/*.js");
}
